// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6bqtXjXdK_wcxAfxZp9GGkpNB7xhrzxI',
    appId: '1:752437812928:web:f77a3e802d451a84bd1725',
    messagingSenderId: '752437812928',
    projectId: 'health-tracker-488df',
    authDomain: 'health-tracker-488df.firebaseapp.com',
    storageBucket: 'health-tracker-488df.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzYWVsHmTwaoxsL7amFplMlwvBVdU4sY8',
    appId: '1:752437812928:android:046d621846eff737bd1725',
    messagingSenderId: '752437812928',
    projectId: 'health-tracker-488df',
    storageBucket: 'health-tracker-488df.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVEVhXCAmmiqUFhtQJkfzGeocGhOYwvmo',
    appId: '1:752437812928:ios:16016681506c5f9bbd1725',
    messagingSenderId: '752437812928',
    projectId: 'health-tracker-488df',
    storageBucket: 'health-tracker-488df.appspot.com',
    iosBundleId: 'com.example.healthTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBVEVhXCAmmiqUFhtQJkfzGeocGhOYwvmo',
    appId: '1:752437812928:ios:d1dee5092014ff1abd1725',
    messagingSenderId: '752437812928',
    projectId: 'health-tracker-488df',
    storageBucket: 'health-tracker-488df.appspot.com',
    iosBundleId: 'com.example.healthTracker.RunnerTests',
  );
}
